// <auto-generated />
using System;
using CarteraClientes.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CarteraClientes.Infrastructure.Persistencia.Migrations
{
    [DbContext(typeof(CarteraClientesDbContext))]
    [Migration("20260714005352_AddRemindersScheduling")]
    partial class AddRemindersScheduling
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CarteraClientes.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClienteId"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("ApellidoMaterno")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("ApellidoPaterno")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Correo")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.HasKey("ClienteId");

                    b.ToTable("Clientes", (string)null);

                    b.HasData(
                        new
                        {
                            ClienteId = 1,
                            Activo = true,
                            ApellidoMaterno = "López",
                            ApellidoPaterno = "Pérez",
                            Correo = "juan.perez@correo.com",
                            Direccion = "León, Guanajuato",
                            FechaRegistro = new DateTime(2026, 7, 13, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Juan",
                            Telefono = "4771234567"
                        });
                });

            modelBuilder.Entity("CarteraClientes.Domain.Entities.Movimiento", b =>
                {
                    b.Property<int>("MovimientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MovimientoId"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime>("FechaMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("VentaId")
                        .HasColumnType("integer");

                    b.HasKey("MovimientoId");

                    b.HasIndex("VentaId");

                    b.ToTable("Movimientos", (string)null);

                    b.HasData(
                        new
                        {
                            MovimientoId = 1,
                            Descripcion = "Cargo inicial por venta de producto",
                            FechaMovimiento = new DateTime(2026, 7, 13, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Monto = 1500.00m,
                            TipoMovimiento = "CARGO",
                            VentaId = 1
                        },
                        new
                        {
                            MovimientoId = 2,
                            Descripcion = "Pago realizado por el cliente",
                            FechaMovimiento = new DateTime(2026, 7, 13, 11, 5, 0, 0, DateTimeKind.Unspecified),
                            Monto = 500.00m,
                            TipoMovimiento = "ABONO",
                            VentaId = 1
                        });
                });

            modelBuilder.Entity("CarteraClientes.Domain.Entities.Pago", b =>
                {
                    b.Property<int>("PagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PagoId"));

                    b.Property<DateTime>("FechaPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("FormaPago")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("MontoPago")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Referencia")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("VentaId")
                        .HasColumnType("integer");

                    b.HasKey("PagoId");

                    b.HasIndex("VentaId");

                    b.ToTable("Pagos", (string)null);

                    b.HasData(
                        new
                        {
                            PagoId = 1,
                            FechaPago = new DateTime(2026, 7, 13, 11, 5, 0, 0, DateTimeKind.Unspecified),
                            FormaPago = "EFECTIVO",
                            MontoPago = 500.00m,
                            Observaciones = "Primer abono",
                            VentaId = 1
                        });
                });

            modelBuilder.Entity("CarteraClientes.Domain.Entities.ProgramacionRecordatorio", b =>
                {
                    b.Property<int>("ProgramacionRecordatorioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProgramacionRecordatorioId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("DiaSemana")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("character varying(15)");

                    b.Property<DateTime?>("FechaHoraEjecucion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaUltimaEjecucion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Frecuencia")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("SEMANAL");

                    b.Property<string>("HoraEjecucion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("character varying(5)")
                        .HasDefaultValue("09:00");

                    b.Property<string>("MensajePersonalizado")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TipoCanal")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("WHATSAPP");

                    b.Property<int>("VentaId")
                        .HasColumnType("integer");

                    b.HasKey("ProgramacionRecordatorioId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("VentaId");

                    b.ToTable("ProgramacionesRecordatorios", (string)null);
                });

            modelBuilder.Entity("CarteraClientes.Domain.Entities.Recordatorio", b =>
                {
                    b.Property<int>("RecordatorioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RecordatorioId"));

                    b.Property<string>("Canal")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("WHATSAPP");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("PENDIENTE");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaEnvio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("FechaProgramada")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("VentaId")
                        .HasColumnType("integer");

                    b.HasKey("RecordatorioId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("VentaId");

                    b.ToTable("Recordatorios", (string)null);
                });

            modelBuilder.Entity("CarteraClientes.Domain.Entities.Venta", b =>
                {
                    b.Property<int>("VentaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VentaId"));

                    b.Property<int>("Cantidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("DescripcionProducto")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("PENDIENTE");

                    b.Property<DateTime>("FechaInicioDeuda")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaLimitePago")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("VentaId");

                    b.HasIndex("ClienteId");

                    b.ToTable("Ventas", (string)null);

                    b.HasData(
                        new
                        {
                            VentaId = 1,
                            Cantidad = 1,
                            ClienteId = 1,
                            DescripcionProducto = "Par de zapatos deportivos talla 27",
                            Estatus = "PENDIENTE",
                            FechaInicioDeuda = new DateTime(2026, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaLimitePago = new DateTime(2026, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaRegistro = new DateTime(2026, 7, 13, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            MontoTotal = 1500.00m,
                            Observaciones = "Venta a crédito",
                            PrecioUnitario = 1500.00m
                        });
                });

            modelBuilder.Entity("CarteraClientes.Domain.Entities.VwCarteraClientes", b =>
                {
                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("Correo")
                        .IsUnicode(false)
                        .HasColumnType("text");

                    b.Property<string>("DescripcionProducto")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("text");

                    b.Property<decimal>("DeudaInicial")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaInicioDeuda")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaLimitePago")
                        .HasColumnType("date");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("text");

                    b.Property<string>("Observaciones")
                        .IsUnicode(false)
                        .HasColumnType("text");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("SaldoPendiente")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Telefono")
                        .IsUnicode(false)
                        .HasColumnType("text");

                    b.Property<decimal>("TotalPagado")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("VentaId")
                        .HasColumnType("integer");

                    b.ToTable((string)null);

                    b.ToView("Vw_CarteraClientes", (string)null);
                });

            modelBuilder.Entity("CarteraClientes.Domain.Entities.Movimiento", b =>
                {
                    b.HasOne("CarteraClientes.Domain.Entities.Venta", "Venta")
                        .WithMany("Movimientos")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("CarteraClientes.Domain.Entities.Pago", b =>
                {
                    b.HasOne("CarteraClientes.Domain.Entities.Venta", "Venta")
                        .WithMany("Pagos")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("CarteraClientes.Domain.Entities.ProgramacionRecordatorio", b =>
                {
                    b.HasOne("CarteraClientes.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarteraClientes.Domain.Entities.Venta", "Venta")
                        .WithMany()
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("CarteraClientes.Domain.Entities.Recordatorio", b =>
                {
                    b.HasOne("CarteraClientes.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Recordatorios")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarteraClientes.Domain.Entities.Venta", "Venta")
                        .WithMany("Recordatorios")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("CarteraClientes.Domain.Entities.Venta", b =>
                {
                    b.HasOne("CarteraClientes.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Ventas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("CarteraClientes.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Recordatorios");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("CarteraClientes.Domain.Entities.Venta", b =>
                {
                    b.Navigation("Movimientos");

                    b.Navigation("Pagos");

                    b.Navigation("Recordatorios");
                });
#pragma warning restore 612, 618
        }
    }
}
